name: "GitOps main"

on:
  push:
    branches:
      - main
      - github-actions

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/aisrael/python-service:${{ github.sha }}
          # build on feature branches, push only on main branch
          push: true

  deploy-minikube:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    environment: minikube
    steps:
      - uses: actions/checkout@v3
      - name: Replace {{ gitHEAD }} with $GITHUB_SHA
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "kubernetes/**"
          find: "{{ gitHEAD }}" # we want to remove ref/heads/ from source
          replace: ${{ github.sha }} # this translates to ref/heads/main on the main branch, but can be any arbitrary string

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: "aisrael/softcon2022"
          token: ${{ secrets.GITOPS_GITHUB_TOKEN }}
          path: ".softcon2022"

      - name: mktemp
        run: |
          TEMP_DIR=$(mktemp -d)
          echo "TEMP_DIR=${TEMP_DIR}" >> $GITHUB_ENV
          mv ".softcon2022/.git" "${TEMP_DIR}/.git"

      - name: Copy templates
        shell: bash
        env:
          USER_NAME: "Alistair Israel"
          USER_EMAIL: "aisrael@gmail.com"
          TARGET_MANIFESTS_DIR: ".softcon2022/python-service/minikube"
        run: |
          TARGET_MANIFESTS_DIR=".softcon2022/python-service/minikube"
          echo "[+] Deleting ${TARGET_MANIFESTS_DIR}"
          rm -rf "${TARGET_MANIFESTS_DIR}"
          echo "[+] Creating (now empty) ${TARGET_MANIFESTS_DIR}"
          mkdir -p "${TARGET_MANIFESTS_DIR}"
          echo "[+] Copying contents of python-service/kubernetes to ${TARGET_MANIFESTS_DIR}"
          echo cp -ra "kubernetes/." "${TARGET_MANIFESTS_DIR}"
          cp -ra "kubernetes/." "${TARGET_MANIFESTS_DIR}"

      - name: Update tag using yq
        id: yq
        uses: mikefarah/yq@v4.25.3
        env:
          PATH_TO_DEPLOYMENT: "kubernetes/deployment.yaml"
          TARGET_MANIFESTS_DIR: ".softcon2022/python-service/minikube"
        with:
          cmd: |
            cat "$PATH_TO_DEPLOYMENT" \
            | yq '.metadata.labels."app.kubernetes.io/version" = "${{ github.sha }}"' \
            | yq '.spec.template.metadata.labels."app.kubernetes.io/version" = "${{ github.sha }}"' \
            | yq '.spec.template.metadata.labels."app.kubernetes.io/version" = "${{ github.sha }}"' \
            > "${TARGET_MANIFESTS_DIR}/deployment.yaml"

      - name: GitOps push
        shell: bash
        env:
          USER_NAME: "Alistair Israel"
          USER_EMAIL: "aisrael@gmail.com"
        run: |
          echo "[+] Push updated manifests to GitOps repo"
          mv "${TEMP_DIR}/.git" ".softcon2022/.git"
          ORIGIN_COMMIT="https://github.com/aisrael/python-service/commit/$GITHUB_SHA"
          COMMIT_MESSAGE="Update from ${ORIGIN_COMMIT}"
          git config --global user.email "${{ env.USER_EMAIL }}"
          git config --global user.name "${{ env.USER_NAME }}"
          cd ".softcon2022"
          git add .
          git status
          git diff-index --quiet HEAD || {
            echo git commit --message "${COMMIT_MESSAGE}"
            git commit --message "${COMMIT_MESSAGE}"
            git push
          }
