name: "CI"

on: push

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7.8"
      - run: pip install -r requirements.txt
      - run: pylint app
      - name: Test with pytest
        run: pytest app

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0

  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
